use std::collections::BTreeSet;

use bfformat::Op;

use crate::target::{Arch, Target};
use crate::{arch, os};

/// Number of cells in the tape. The native backend trades bfrun's growable
/// tape for one fixed, zero-initialized allocation, because native code can't
/// grow a buffer transparently the way a Rust `Vec` does — the cell pointer
/// would have to be re-derived from a base register kept somewhere stable
/// after every reallocation, which is a lot of machinery for a case no real
/// program hits. 16 MiB lives in .bss, so it costs no file size and no
/// committed memory until touched.
///
/// The divergence from `bfrun`, stated plainly: a program that moves right
/// past 16 MiB of cells, or left of cell 0, gets undefined behavior here
/// (almost certainly a crash) where bfrun would grow the tape or exit with a
/// pointer-underflow error. Normal programs — even tape-hungry ones like
/// mandelbrot — use a few thousand cells.
pub const TAPE_SIZE: u64 = 16 * 1024 * 1024;

/// Label for the code of op `index`. bfc stores a jump's `target` as the
/// index of the bracket op it's paired with, and bfrun's dispatch loop does
/// `pc = target; pc += 1` — so a taken jump always executes op `target + 1`
/// next. Branches therefore aim at `op_label(target + 1)`, and
/// `index == ops.len()` is the exit label, for loops whose closing bracket is
/// the final op.
pub fn op_label(index: usize) -> String {
    format!(".Lop{index}")
}

/// Appends one line of assembly (no trailing newline in `text`).
pub(crate) fn line(out: &mut String, text: &str) {
    out.push_str(text);
    out.push('\n');
}

/// Emits a complete assembly file implementing `ops` for `target`: a header,
/// the OS-specific entry sequence, one lowering per op, the exit sequence,
/// and the tape allocation.
pub fn emit_assembly(ops: &[Op], target: Target) -> String {
    let mut out = String::new();
    let comment = arch::comment_prefix(target.arch);

    line(
        &mut out,
        &format!("{comment} generated by bfnative, target: {target}"),
    );
    if target.arch == Arch::X86_64 {
        // The x86 backend emits Intel syntax; this directive makes the
        // dialect explicit so any assembler's default doesn't matter.
        line(&mut out, ".intel_syntax noprefix");
    }
    line(&mut out, ".text");

    os::emit_prologue(&mut out, target);

    // Op indices some branch lands on (each jump's target + 1 — see
    // op_label). Sorting via BTreeSet just keeps the set's construction
    // deterministic; emission order is the op order either way.
    let mut branch_targets: BTreeSet<usize> = ops
        .iter()
        .filter_map(|op| match op {
            Op::JumpIfZero { target } | Op::JumpIfNonZero { target } => Some(*target as usize + 1),
            _ => None,
        })
        .collect();
    branch_targets.insert(ops.len());

    for (index, op) in ops.iter().enumerate() {
        if branch_targets.contains(&index) {
            line(&mut out, &format!("{}:", op_label(index)));
        }
        line(&mut out, &format!("    {comment} {index}: {op:?}"));

        match op {
            // I/O lowering is entirely OS-specific: which registers arguments
            // go in, whether it's a syscall or a libc or Win32 call.
            Op::Output => os::emit_output(&mut out, target),
            Op::Input => os::emit_input(&mut out, target),
            // Everything else is pure instruction selection for the arch.
            op => arch::emit_op(&mut out, target.arch, op),
        }
    }

    // Landing pad for jumps past the final op (and always present so the
    // exit sequence has a name, which keeps hand-reading the output easier).
    line(&mut out, &format!("{}:", op_label(ops.len())));

    os::emit_epilogue(&mut out, target);
    os::emit_globals(&mut out, target);

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::target::ALL_TARGETS;

    fn asm_for(ops: &[Op], target_name: &str) -> String {
        emit_assembly(ops, Target::from_name(target_name).unwrap())
    }

    #[test]
    fn x86_64_add_and_sub_touch_the_cell_in_memory() {
        let asm = asm_for(&[Op::Add(5), Op::Sub(2)], "linux-x86_64");
        assert!(asm.contains("add byte ptr [rbx], 5"));
        assert!(asm.contains("sub byte ptr [rbx], 2"));
    }

    #[test]
    fn x86_64_zero_is_a_single_store() {
        let asm = asm_for(&[Op::Zero], "linux-x86_64");
        assert!(asm.contains("mov byte ptr [rbx], 0"));
    }

    #[test]
    fn x86_64_jumps_land_one_op_past_their_target() {
        // The shape `+[-]` has after parsing (the optimizer would fold it to
        // a Zero; hand-built here to check the raw lowering).
        let ops = [
            Op::Add(1),
            Op::JumpIfZero { target: 3 },
            Op::Sub(1),
            Op::JumpIfNonZero { target: 1 },
        ];
        let asm = asm_for(&ops, "linux-x86_64");

        // JumpIfZero { 3 } lands on op 4 == the exit label; the back edge of
        // JumpIfNonZero { 1 } lands on op 2, the loop body.
        assert!(asm.contains("cmp byte ptr [rbx], 0"));
        assert!(asm.contains("je .Lop4"));
        assert!(asm.contains("jne .Lop2"));
        assert!(asm.contains(".Lop2:"));
        assert!(asm.contains(".Lop4:"));
        assert!(asm.contains("xor edi, edi"));
    }

    #[test]
    fn x86_64_small_pointer_moves_are_single_instructions() {
        let asm = asm_for(
            &[Op::MoveRight(100_000), Op::MoveLeft(100_000)],
            "linux-x86_64",
        );
        assert!(asm.contains("add rbx, 100000"));
        assert!(asm.contains("sub rbx, 100000"));
        // (the epilogue's own `mov eax, 231` is the exit syscall number, so
        // the check for the constant-load path has to be more specific)
        assert!(!asm.contains("mov eax, 0x"));
        assert!(!asm.contains("add rbx, rax"));
    }

    #[test]
    fn x86_64_huge_pointer_moves_go_through_a_register() {
        // add/sub rbx, imm32 sign-extends, so a count this large can't be
        // encoded as a direct immediate.
        let asm = asm_for(&[Op::MoveRight(0xF000_0000)], "linux-x86_64");
        assert!(asm.contains("mov eax, 0xf0000000"));
        assert!(asm.contains("add rbx, rax"));
    }

    #[test]
    fn aarch64_add_and_sub_wrap_through_strb() {
        let asm = asm_for(&[Op::Add(5), Op::Sub(2)], "linux-aarch64");
        assert!(asm.contains("ldrb w0, [x19]"));
        assert!(asm.contains("add w0, w0, #5"));
        assert!(asm.contains("sub w0, w0, #2"));
        assert!(asm.contains("strb w0, [x19]"));
    }

    #[test]
    fn aarch64_zero_is_a_single_store() {
        let asm = asm_for(&[Op::Zero], "linux-aarch64");
        assert!(asm.contains("strb wzr, [x19]"));
    }

    #[test]
    fn aarch64_jumps_use_cbz_and_cbnz() {
        let ops = [
            Op::Add(1),
            Op::JumpIfZero { target: 3 },
            Op::Sub(1),
            Op::JumpIfNonZero { target: 1 },
        ];
        let asm = asm_for(&ops, "linux-aarch64");
        assert!(asm.contains("ldrb w0, [x19]"));
        assert!(asm.contains("cbz w0, .Lop4"));
        assert!(asm.contains("cbnz w0, .Lop2"));
    }

    #[test]
    fn aarch64_small_pointer_moves_are_single_instructions() {
        let asm = asm_for(&[Op::MoveLeft(100)], "linux-aarch64");
        assert!(asm.contains("sub x19, x19, #100"));
        assert!(!asm.contains("movz"));
    }

    #[test]
    fn aarch64_big_pointer_moves_use_movz_movk() {
        let asm = asm_for(&[Op::MoveRight(0x1234_5678)], "linux-aarch64");
        assert!(asm.contains("movz w0, #0x5678"));
        assert!(asm.contains("movk w0, #0x1234, lsl #16"));
        assert!(asm.contains("add x19, x19, x0"));
    }

    #[test]
    fn linux_uses_raw_syscalls_on_both_arches() {
        let x86 = asm_for(&[Op::Output, Op::Input], "linux-x86_64");
        assert!(x86.contains("mov eax, 1"));
        assert!(x86.contains("xor eax, eax"));
        assert!(x86.contains("syscall"));
        assert!(x86.contains("_start:"));

        let arm = asm_for(&[Op::Output, Op::Input], "linux-aarch64");
        assert!(arm.contains("mov x8, #64"));
        assert!(arm.contains("mov x8, #63"));
        assert!(arm.contains("svc 0"));
        // exit_group(0)
        assert!(arm.contains("mov x8, #94"));
    }

    #[test]
    fn macos_symbols_carry_leading_underscores() {
        let x86 = asm_for(&[Op::Output, Op::Input], "macos-x86_64");
        assert!(x86.contains("_main:"));
        assert!(x86.contains("lea rbx, [rip + _tape]"));
        assert!(x86.contains("call _write"));
        assert!(x86.contains("call _read"));

        let arm = asm_for(&[Op::Output], "macos-aarch64");
        assert!(arm.contains("bl _write"));
        // arm64 Mach-O requires ADRP against a named symbol to be
        // GOT-relative; the tape address comes through a GOT indirection.
        assert!(arm.contains("adrp x19, _tape@GOTPAGE"));
        assert!(arm.contains("ldr x19, [x19, _tape@GOTPAGEOFF]"));
    }

    #[test]
    fn macos_preserves_the_callee_saved_cell_register() {
        let x86 = asm_for(&[], "macos-x86_64");
        assert!(x86.contains("push rbx"));
        assert!(x86.contains("pop rbx"));

        let arm = asm_for(&[], "macos-aarch64");
        assert!(arm.contains("str x19, [sp, #-16]!"));
        assert!(arm.contains("ldr x19, [sp], #16"));
    }

    #[test]
    fn windows_x86_64_sets_up_a_win64_call_frame() {
        let asm = asm_for(&[Op::Output, Op::Input], "windows-x86_64");
        assert!(asm.contains("bf_start:"));
        assert!(asm.contains("and rsp, -16"));
        assert!(asm.contains("sub rsp, 0x30"));
        // GetStdHandle constants, one per I/O op: -11 for output, -10 in.
        assert!(asm.contains("mov ecx, -11"));
        assert!(asm.contains("mov ecx, -10"));
        assert!(asm.contains("call GetStdHandle"));
        assert!(asm.contains("call WriteFile"));
        assert!(asm.contains("call ReadFile"));
        // The lpOverlapsed (5th) argument slot at [rsp+0x20] must be NULL.
        assert!(asm.contains("mov qword ptr [rsp+0x20], 0"));
        assert!(asm.contains("call ExitProcess"));
    }

    #[test]
    fn windows_aarch64_uses_win32_calls_not_crt() {
        let asm = asm_for(&[Op::Output, Op::Input], "windows-aarch64");
        assert!(asm.contains("bf_start:"));
        // movn w0, #10 == ~10 == 0xFFFFFFF5 == STD_OUTPUT_HANDLE, and
        // movn w0, #9 == STD_INPUT_HANDLE.
        assert!(asm.contains("movn w0, #10"));
        assert!(asm.contains("movn w0, #9"));
        assert!(asm.contains("bl GetStdHandle"));
        assert!(asm.contains("bl WriteFile"));
        assert!(asm.contains("bl ReadFile"));
        assert!(asm.contains("bl ExitProcess"));
        // ReadFile/WriteFile need a writable DWORD for the byte count; the
        // stack slot at [sp] (frame reserved in the prologue) serves.
        assert!(asm.contains("mov x3, sp"));
        assert!(asm.contains("mov x4, xzr"));
    }

    #[test]
    fn every_target_allocates_a_zeroed_tape() {
        for target in ALL_TARGETS {
            let asm = asm_for(&[Op::Zero], &target.name());
            let expected = match target.os {
                crate::target::Os::Macos => {
                    format!(".zerofill __DATA,__bss,_tape,{}", TAPE_SIZE)
                }
                _ => format!(".comm tape, {}", TAPE_SIZE),
            };
            assert!(asm.contains(&expected), "missing tape in {}", target.name());
        }
    }

    #[test]
    fn every_branch_has_a_landing_label() {
        // Through the real front end, so the op shapes are the ones the
        // optimizer actually produces.
        let source = "++[>+[-]<-]>[-]";
        let ops = bfc::optimize::optimize(bfc::parser::parse(source).unwrap());
        for name in ALL_TARGETS.iter().map(|t| t.name()) {
            let asm = asm_for(&ops, &name);
            for op in &ops {
                if let Op::JumpIfZero { target } | Op::JumpIfNonZero { target } = op {
                    assert!(
                        asm.contains(&format!("{}:", op_label(*target as usize + 1))),
                        "{name} is missing a label for jump target {target}"
                    );
                }
            }
        }
    }

    #[test]
    fn empty_program_is_just_entry_and_exit() {
        let asm = asm_for(&[], "linux-x86_64");
        assert!(asm.contains("_start:"));
        assert!(asm.contains(".Lop0:"));
        assert!(asm.contains("mov eax, 231"));
    }
}
